apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spring-cloud-gateway
secretGenerator:
- name: animal-rescue-sso
  envs:
  - secrets/test-sso-credentials.txt
  type: Opaque

generatorOptions:
  disableNameSuffixHash: true
