apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: animal-rescue-backend-route-config
spec:
  service:
    name: animal-rescue-backend
  routes:
    - predicates:
        - Path=/api/animals
        - Method=GET
      filters:
        - RateLimit=2,10s
      tags:
        - "pet adoption"
    - predicates:
        - Path=/api/actuator/**
      tags:
        - actuator
    - ssoEnabled: true
      tokenRelay: true
      predicates:
        - Path=/api/whoami
        - Method=GET
      tags:
        - sso
    - ssoEnabled: true
      tokenRelay: true
      predicates:
        - Path=/api/animals/*/adoption-requests/**
        - Method=POST,PUT,DELETE
      tags:
        - "pet adoption"
      model:
        requestBody:
          description: Manage adoption requests
          content:
            'application/json':
              schema:
                type: object
                description: Adoption request schema
                properties:
                  adopterName:
                    type: string
                  email:
                    type: string
                    format: email
                  notes:
                    type: string
                required: [ "adopterName", "email" ]
