apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: animal-rescue-backend-route-config
spec:
  service:
    name: animal-rescue-backend
  routes:
    - predicates:
        - Path=/api/animals
        - Method=GET
      filters:
        - RateLimit=2,10s
      tags:
        - "pet adoption"
      title: "Retrieve pets for adoption."
      description: "Retrieve all of the animals who are up for pet adoption."
    - predicates:
        - Path=/api/actuator/**
      tags:
        - actuator
      title: "API Actuator endpoints"
      description: "Access API actuator endpoints to provide current status of backend service."
    - ssoEnabled: true
      tokenRelay: true
      predicates:
        - Path=/api/whoami
        - Method=GET
      tags:
        - sso
      title: "Retrieve user information"
      description: "Retrieve the current authenticated user's information."
    - ssoEnabled: true
      tokenRelay: true
      predicates:
        - Path=/api/animals/*/adoption-requests/**
        - Method=POST,PUT,DELETE
      tags:
        - "pet adoption"
      title: "Pet adoption API"
      description: "Manage pet adoptions."
      model:
        requestBody:
          description: Manage adoption requests
          content:
            'application/json':
              schema:
                type: object
                description: Adoption request schema
                properties:
                  adopterName:
                    type: string
                  email:
                    type: string
                    format: email
                  notes:
                    type: string
                required: [ "adopterName", "email" ]
