apiVersion: skaffold/v2beta22
kind: Config
build:
  artifacts:
  - image: springcloudservices/animal-rescue-backend
    context: backend
    buildpacks:
      builder: gcr.io/paketo-buildpacks/builder:base
      dependencies:
        paths:
        - src/main/**
        - build.gradle
        - settings.gradle
  - image: springcloudservices/animal-rescue-frontend
    # context: frontend
    custom:
      buildCommand: |
        ./gradlew :frontend:assemble && docker build frontend -t springcloudservices/animal-rescue-frontend:latest
      dependencies:
        paths:
        - frontend/src/**
        - frontend/build.gradle
  tagPolicy:
    sha256: {}
deploy:
  kustomize:
    paths:
    - ./
    - gateway/sso-secret-for-gateway/
