apiVersion: skaffold/v2beta6
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: springcloudservices/animal-rescue-backend
    context: backend
    buildpacks:
      builder: gcr.io/paketo-buildpacks/builder:base-platform-api-latest
      dependencies:
        paths:
        - src/main/**
        - build.gradle
        - settings.gradle

deploy:
  kustomize:
    paths:
      - k8s/base
profiles:
  - name: harbor-registry
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: dev.registry.pivotal.io/spring-cloud-gateway/animal-rescue-backend
      - op: replace
        path: /deploy/kustomize/paths/0
        value: k8s/overlays/harbor-registry
  - name: ingress
    patches:
      - op: add
        path: /deploy/kustomize/paths
        value: [k8s/overlays/ingress]
