apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: dekt-animals-gateway
spec:
  api:
    serverUrl: https://animals.apps.dekt.io
    title: Animals rescue
    description: APIs for building the animal rescue online store. 
    version: 0.1.0
  count: 2
  sso:
    secret: dekt-animals-sso