apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: gateway-demo
spec:
  api:
    serverUrl: http://animal-rescue.my.domain.io:8081
    title: "Animal Rescue"
    description: "Sample application for Spring Cloud Gateway commercial product demos."
    documentation: "https://github.com/spring-cloud-services-samples/animal-rescue/"
    version: "1.0.0-K8s"
    cors:
      allowedOrigins:
        - "*"
      allowedMethods:
        - "*"
      allowedHeaders:
        - "*"
  env:
    - name: server.servlet.session.cookie.name
      value: "FRED-COOKIE"
  count: 2
  sso:
    secret: animal-rescue-sso
    roles-attribute-name: "groups"
  observability:
    metrics:
      prometheus:
        enabled: true
        annotations:
          enabled: true
    wavefront:
      secret: metrics-secret
      application: animal-rescue
      service: animal-rescue-gateway
