apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: gateway-demo
spec:
  api:
serverUrl: 
    serverUrl: http://animal-rescue.my.domain.io
    title: "Animal Rescue"
    description: "Sample application for Spring Cloud Gateway commercial product demos."
    documentation: "https://github.com/spring-cloud-services-samples/animal-rescue/"
    version: "1.0.0-K8s"
    cors:
      allowedOrigins:
        - "http://api-portal.my.domain.io"
  count: 2
  sso:
    secret: animal-rescue-sso
