apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: gateway-demo
  annotations:
    apis.tanzu.vmare.com/api-title: "Animal Rescue"
    apis.tanzu.vmare.com/api-description: "Sample application for Spring Cloud Gateway commercial product demos."
    apis.tanzu.vmare.com/api-documentation: "https://github.com/spring-cloud-services-samples/animal-rescue/"
spec:
  api:
    serverUrl: http://animal-rescue.my.domain.io
    version: "1.0.0-K8s"
    cors:
      allowedOrigins:
      - "http://api-portal.my.domain.io"
  count: 2
  sso:
    secret: animal-rescue-sso

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-demo
  labels:
    app: gateway-demo
spec:
  rules:
  - host: animal-rescue.my.domain.io
    http:
      paths:
      - backend:
          service:
            name: gateway-demo
            port:
              number: 80
        pathType: ImplementationSpecific
