apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: dekt-animals-backend-route-config
spec:
  service: 
    name: dekt-animals-backend-service
  routes:
    - predicates:
        - Path=/api/animals
        - Method=GET
      filters:
        - RateLimit=2,15s
    - predicates:
        - Path=/api/whoami
        - Method=GET
      ssoEnabled: true
      tokenRelay: true
    - predicates:
        - Path=/api/animals/*/adoption-requests/**
        - Method=POST,PUT,DELETE
      ssoEnabled: true
      tokenRelay: true
     predicates:
        - Path=/api/dekt
        - Method=GET
