apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dekt-apps

resources:
  - dekt-animals-backend.yaml
  - dekt-animals-backend-route-config.yaml
  - dekt-animals-backend-mapping.yaml
  
