apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: dekt-animals-frontend-route-config
spec:
  service: 
    name: dekt-animals-frontend-service
  routes:
    - predicates:
        - Path=/rescue/login
        - Method=GET
      filters:
        - RedirectTo=302, /rescue
      ssoEnabled: true
      order: 0
    - predicates:
        - Path=/rescue/**
        - Method=GET
      order: 1000

