---
aliases:
- &slack-success-notification
  put: alert
  params:
    icon_emoji: ":demogorgon:"
    username: concourse
    channel: ((scs-slack-notification-channel))
    text: |
      SCG sample app has updated in the demo environment

- &slack-failure-notification
  put: alert
  params: &slack-failure-params
    icon_emoji: ":demogorgon:"
    username: concourse
    channel: ((scs-slack-failure-channel))
    text: |
      <!here> Build <https://scs.ci.springapps.io/builds/$BUILD_ID|$BUILD_NAME> failed to update the sample app in the demo environment

groups:
  - name: "Build and Push"
    jobs: ["test-all", "build-and-deploy"]
  - name: "CI Images"
    jobs: ["build-release-ci-images"]

jobs:
- name: build-release-ci-images
  plan:
  - get: ci-images-git-repo
    trigger: true
  - put: release-ci-image
    params:
      build: ci-images-git-repo/concourse/images/release-ci-image
  on_failure:
    <<: *slack-failure-notification
    params:
      <<: *slack-failure-params
      text: |
        <!here> Build <https://scs.ci.springapps.io/builds/$BUILD_ID|$BUILD_NAME> failed to release CI image

- name: test-all
  plan:
  - get: sample-src
    trigger: true
  - task: test
    file: sample-src/concourse/tasks/test.yml
  on_failure: *slack-failure-notification

- name: build-and-deploy
  plan:
  - get: sample-src
    trigger: true
    passed: [test-all]
  - task: deploy
    file: sample-src/concourse/tasks/deploy.yml

  on_success: *slack-success-notification
  on_failure: *slack-failure-notification

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: alert
  type: slack-notification
  source:
    # Default channel is #scs-firehose
    url: ((scs-slack-webhook))

- name: sample-src
  type: git
  icon: github-circle
  source:
    uri: ((github-repo))
    branch: ((branch))

- name: ci-images-git-repo
  type: git
  source:
    uri: ((github-repo))
    branch: ((branch))
    paths: ["concourse/images/*"]

- name: release-ci-image
  type: docker-image
  source:
    repository: springcloudservices/animal-rescue-ci
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: ((branch))
