---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springcloudservices/animal-rescue-ci
    tag: ((branch))

inputs:
- name: sample-src

caches:
  - path: .gradle/
  - path: .m2/
  - path: frontend/node_modules

run:
  path: sample-src/concourse/tasks/deploy.sh

params:
  SRC_PATH: sample-src
  CF_ORG: ((CF_ORG))
  CF_SPACE: ((CF_SPACE))
  CF_API_HOST: ((CF_API_HOST))
  CF_USERNAME: ((CF_USERNAME))
  CF_PASSWORD: ((CF_PASSWORD))
  SKIP_SSL_VALIDATION: ((SKIP_SSL_VALIDATION))
