---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springcloudservices/animal-rescue-ci
    tag: ((branch))

inputs:
- name: sample-src

caches:
  - path: .gradle/
  - path: .m2/
  - path: frontend/node_modules
  - path: e2e/node_modules

run:
  path: sample-src/concourse/tasks/test.sh

params:
  SRC_PATH: sample-src
