management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging.level:
  org.springframework.data: debug

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://any.uaa.uri/token_keys
