apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-rescue-backend
spec:
  selector:
    matchLabels:
      app: animal-rescue-backend
  template:
    metadata:
      labels:
        app: animal-rescue-backend
    spec:
      containers:
        - name: animal-rescue-backend
          image: springcloudservices/animal-rescue-backend
          env:
            - name: spring.profiles.active
              value: k8s
            - name: spring.security.oauth2.resourceserver.jwt.jwk-set-uri
              valueFrom:
                secretKeyRef:
                  name: sso-credentials
                  key: jwk-set-uri
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: animal-rescue-backend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: animal-rescue-backend

---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayBinding
metadata:
  name: animal-rescue-backend-routes
spec:
  gateway: gateway-demo-with-dynamic-routes
  service: animal-rescue-backend
  routes:
    - predicates:
        - Path=/api/animals
        - Method=GET
      filters:
        - StripPrefix=1
#        - RateLimit=2,10s
    - ssoEnabled: true
      tokenRelay: true
      predicates:
        - Path=/api/whoami
        - Method=GET
      filters:
        - StripPrefix=1
    - ssoEnabled: true
      tokenRelay: true
      predicates:
        - Path=/api/animals/*/adoption-requests/**
        - Method=POST,PUT,DELETE
      filters:
        - StripPrefix=1
