apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: animal-rescue-backend-route-config
spec:
  service:
    name: animal-rescue-backend
  routes:
    - predicates:
        - Path=/api/animals
        - Method=GET
      filters:
        - StripPrefix=1
        - RateLimit=2,10s
    - ssoEnabled: true
      tokenRelay: true
      predicates:
        - Path=/api/whoami
        - Method=GET
      filters:
        - StripPrefix=1
    - ssoEnabled: true
      tokenRelay: true
      predicates:
        - Path=/api/animals/*/adoption-requests/**
        - Method=POST,PUT,DELETE
      filters:
        - StripPrefix=1
