apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: animal-rescue

secretGenerator:
- name: sso-credentials
  envs:
  - secrets/sso-credentials-for-backend.txt
  type: Opaque

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - animal-rescue-frontend.yaml
  - animal-rescue-frontend-mapping.yaml
  - animal-rescue-frontend-route-config.yaml
  - animal-rescue-backend.yaml
  - animal-rescue-backend-mapping.yaml
  - animal-rescue-backend-route-config.yaml
  - gateway-demo.yaml
