apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: animal-rescue
secretGenerator:
- name: gateway-sso-credentials
  envs:
  - secrets/test-sso-credentials.txt
  type: Opaque

generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - animal-rescue-frontend.yaml
  - animal-rescue-backend.yaml
  - gateway-demo.yaml
